version: "3"
services:
  server:
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo
    volumes:
      - /srv/KilnRegulator:/data/db
    ports:
      - "27017:27017"
