FROM debian:stable-slim

ENV ARDUINO_DIR=/arduino-1.8.7 PATH="${PATH}:/arduino-1.8.7"

RUN apt update && apt install -y wget xz-utils make git python python-serial

RUN wget -q -O- https://downloads.arduino.cc/arduino-1.8.7-linuxarm.tar.xz | tar xJC /

# copy parent directory since its run with parent docker-compose. Required to get .git for submodules
COPY . .

WORKDIR /arduino

RUN git submodule update --init
RUN make

CMD [ "make", "upload" ]
