const TIME_ORIGIN = 0;
const TEMP_ORIGIN = 0;

const NO_PROG_SELECTED = "";

//Keys
const DURATION = "duration";
const SLOPE = "slope";
const TARGET_TEMPERATURE = "targetTemperature";
const ID = "_id";
const TABLE_KEYS = [DURATION, SLOPE, TARGET_TEMPERATURE];

//Actions
const SELECT_PROGRAM = "SELECT_PROGRAM";
const ADD_PROGRAM = "ADD_PROGRAM";
const DELETE_PROGRAM = "DELETE_PROGRAM";
const UPDATE_PROGRAMS = "UPDATE_PROGRAMS";

export {
    TIME_ORIGIN, TEMP_ORIGIN, NO_PROG_SELECTED, DURATION, SLOPE, TARGET_TEMPERATURE, ID, TABLE_KEYS,
    SELECT_PROGRAM, ADD_PROGRAM, DELETE_PROGRAM, UPDATE_PROGRAMS
}