const images = {
    hamburger: require('../assets/menu.png'),
    minus: require('../assets/minus.png'),
    arrow: require('../assets/left_arrow.png'),
    heating: require('../assets/heating.png'),
    cooling: require('../assets/cooling.png'),
    stale: require('../assets/stale.png'),
    time: require('../assets/time.png'),
    loading: require('../assets/loading.gif'),
    error_notif: require('../assets/error_notif.png'),
    bell: require('../assets/bell.png'),
    warning: require('../assets/warning.png'),
    error: require('../assets/error.png'),
    fatal: require('../assets/fatal.png'),
    panic: require('../assets/panic.png'),
    garbage: require('../assets/garbage.png'),
    settings: require('../assets/settings.png'),
    import: require('../assets/import.png'),
    export: require('../assets/export.png'),
    edit: require('../assets/edit.png'),
    duplicate: require('../assets/duplicate.png'),
    history: require('../assets/history.png'),
    error_settings: require('../assets/error_settings.png'),
};

export default images;
