swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "KilnRegulator"
  contact:
    url: "https://github.com/jdeantoni/KilnRegulator3.0/issues"
  license:
    name: "MIT"
host: "127.0.0.1:3000"
basePath: "/"
tags:
- name: "status"
- name: "cooking"
- name: "programs"
- name: "action"
- name: "debug"
- name: "errors"
schemes:
- "http"
paths:
  /status:
    get:
      tags:
      - "status"
      summary: "Get current status of oven"
      operationId: "getStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
  /status/cooking:
    get:
      tags:
      - "status"
      summary: "Get current cooking info from the beginning"
      operationId: "getCurrentCooking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cooking"

  /programs:
    get:
      tags:
      - "programs"
      summary: "Get all programs"
      operationId: "getPrograms"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "all programs"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Program"
    post:
      tags:
      - "programs"
      summary: "add new program"
      operationId: "addProgram"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Program"
      responses:
        200:
          description: "successful operation"
        409:
          description: "program already exists (uuid not unique)"
  /programs/{uuid}:
    put:
      tags:
      - "programs"
      summary: "edit program, ie. archive old program if referenced or delete it, and add new program"
      operationId: "editProgram"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          $ref: "#/definitions/Program"
      - in: "path"
        name: "uuid"
        required: true
        schema:
          type: "string"
          description: "Program UUID to edit"
          format: "uuid"
      responses:
        200:
          description: "successful operation"

  /action/start:
    post:
      tags:
      - "action"
      summary: "Start cooking"
      operationId: "startCooking"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "string"
          descrition: "UUID of program to start on oven"
          format: "uuid"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid operation, ex. already started"
        500:
          description: "could not start cooking"
  /action/stop:
    post:
      tags:
      - "action"
      summary: "Stop cooking"
      operationId: "stopCooking"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid operation, ex. not running"
        500:
          description: "could not stop cooking"

  /action/emergencystop:
    post:
      tags:
      - "action"
      summary: "PANIC"
      operationId: "emergencyStop"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid operation, ex. not running"
        500:
          description: "could not stop cooking"

  /errors:
    get:
      tags:
      - "errors"
      summary: "Get error if any"
      operationId: "getError"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "message"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Error"
    delete:
      tags:
      - "errors"
      summary: "Clear error if any"
      operationId: "clearError"
      consumes:
      - "application/json"
      produces:
      - "application/json"

  /debug:
    get:
      tags:
      - "debug"
      summary: "Get current status of oven with debugging info"
      operationId: "getDebug"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Debug"
    post:
      tags:
      - "debug"
      summary: "set target temperature"
      operationId: "setSetpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            setpoint:
              type: "number"
              format: "double"
      responses:
        200:
          description: "successful operation"




definitions:
  Status:
    type: "object"
    properties:
      errored:
        type: "boolean"
      state:
        type: "string"
        enum:
        - "ready"
        - "running"
        - "stopped"
        - "error"
      elementState:
        type: "string"
        enum:
        - "heating"
        - "stale"
        - "cooling"
      sample:
        $ref: "#/definitions/Sample"
  Debug:
    type: "object"
    properties:
      state:
        type: "string"
        enum:
        - "ready"
        - "running"
        - "stopped"
        - "error"
      elementState:
        type: "string"
        enum:
        - "heating"
        - "stale"
        - "cooling"
      sample:
        $ref: "#/definitions/Sample"
      segment:
        type: "integer"
        format: "int32"
  Segment:
    type: "object"
    properties:
      targetTemperature:
        type: "integer"
        description: "target temperature at the end of the segment"
        format: "int64"
      slope:
        type: "number"
        description: "slope in °C/second"
        format: "float"
      duration:
        type: "integer"
        description: "duration in seconds"
        format: "int64"
  Program:
    type: "object"
    properties:
      uuid:
        type: "string"
        description: "Program UUID used for this cooking"
        format: "uuid"
      name:
        type: "string"
        description: "Program name"
      lastModificationDate:
        type: "string"
        description: "Date and time when this program was last modified"
        format: "date-time"
      segments:
        type: "array"
        items:
          $ref: "#/definitions/Segment"
  Sample:
    type: "object"
    properties:
      timestamp:
        type: "integer"
        description: "timestamp relative to startDate"
        format: "int64"
      temperature:
        type: "number"
        format: "float"
  Cooking:
    type: "object"
    properties:
      programId:
        type: "string"
        description: "Program UUID used for this cooking"
        format: "uuid"
      startDate:
        type: "string"
        description: "Date and time when this cooking started"
        format: "date-time"
      samples:
        type: "array"
        items:
          $ref: "#/definitions/Sample"
      error:
        type: "string"
        description: "If present something bad happened"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "see errorcode.txt"
        format: "int32"
      message:
        type: "string"
