swagger: "2.0"
info:
  description: ""
  version: "0.1.0"
  title: "KilnRegulator"
  contact:
    url: "https://github.com/jdeantoni/KilnRegulator3.0/issues"
  license:
    name: "MIT"
host: "petstore.swagger.io"
basePath: "/"
tags:
- name: "status"
- name: "cooking"
- name: "program"
- name: "action"
- name: "debug"
schemes:
- "https"
- "http"
paths:
  /status:
    get:
      tags:
      - "status"
      summary: "Get current status of oven"
      operationId: "getStatus"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Status"
  /status/error:
    get:
      tags:
      - "status"
      summary: "Get error if any"
      operationId: "getError"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "message"
          schema:
            $ref: "#/definitions/Error"
  /status/cooking:
    get:
      tags:
      - "status"
      summary: "Get current cooking info from the beginning"
      operationId: "getCurrentCooking"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Cooking"
  
  /action/start:
    post:
      tags:
      - "action"
      summary: "Start cooking"
      operationId: "startCooking"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid operation, ex. already started"
        500:
          description: "could not start cooking"
  /action/stop:
    post:
      tags:
      - "action"
      summary: "Stop cooking"
      operationId: "stopCooking"
      responses:
        200:
          description: "successful operation"
        400:
          description: "invalid operation, ex. not running"
        500:
          description: "could not stop cooking"
    
  /debug:
    get:
      tags:
      - "debug"
      summary: "Get current status of oven with debugging info"
      operationId: "getDebug"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Debug"
    post:
      tags:
      - "debug"
      summary: "set target temperature"
      operationId: "setSetpoint"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        required: true
        schema:
          type: "object"
          properties:
            setpoint:
              type: "number"
              format: "double"
      responses:
        200:
          description: "successful operation"

    
    
    
definitions:
  Status:
    type: "object"
    properties:
      state:
        type: "string"
        enum:
        - "ready"
        - "running"
        - "stopped"
        - "error"
      elementState:
        type: "string"
        enum:
        - "heating"
        - "stale"
        - "cooling"
      sample:
        $ref: "#/definitions/Sample"
  Debug:
    type: "object"
    properties:
      state:
        type: "string"
        enum:
        - "ready"
        - "running"
        - "stopped"
        - "error"
      elementState:
        type: "string"
        enum:
        - "heating"
        - "stale"
        - "cooling"
      sample:
        $ref: "#/definitions/Sample"
      segment:
        type: "integer"
        format: "int32"
  Sample:
    type: "object"
    properties:
      timestamp:
        type: "integer"
        description: "timestamp relative to startDate"
        format: "int64"
      temperature:
        type: "number"
        format: "float"
  Cooking:
    type: "object"
    properties:
      programId:
        type: "string"
        description: "Program UUID used for this cooking"
        format: "uuid"
      startDate:
        type: "string"
        description: "Date and time when this cooking started"
        format: "date-time"
      samples:
        $ref: "#/definitions/Sample"
      error:
        type: "string"
        description: "If present something bad happened"
  Error:
    type: "object"
    properties:
      code:
        type: "integer"
        description: "see errorcode.txt"
        format: "int32"
      message:
        type: "string"