/**
 * KilnRegulator
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.0-SNAPSHOT
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Cooking'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/Cooking'));
  } else {
    // Browser globals (root is window)
    if (!root.KilnRegulator) {
      root.KilnRegulator = {};
    }
    root.KilnRegulator.CookingsApi = factory(root.KilnRegulator.ApiClient, root.KilnRegulator.Cooking);
  }
}(this, function(ApiClient, Cooking) {
  'use strict';

  /**
   * Cookings service.
   * @module api/CookingsApi
   * @version 0.1.0
   */

  /**
   * Constructs a new CookingsApi. 
   * @alias module:api/CookingsApi
   * @class
   * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getCooking operation.
     * @callback module:api/CookingsApi~getCookingCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Cooking>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * get the cooking with the given uuid (including all samples)
     * @param {String} uuid 
     * @param {module:api/CookingsApi~getCookingCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Cooking>}
     */
    this.getCooking = function(uuid, callback) {
      var postBody = null;

      // verify the required parameter 'uuid' is set
      if (uuid === undefined || uuid === null) {
        throw new Error("Missing the required parameter 'uuid' when calling getCooking");
      }


      var pathParams = {
        'uuid': uuid
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Cooking];

      return this.apiClient.callApi(
        '/cookings/{uuid}', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the getCookings operation.
     * @callback module:api/CookingsApi~getCookingsCallback
     * @param {String} error Error message, if any.
     * @param {Array.<module:model/Cooking>} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get all cookings uuid/programId/date (without samples)
     * @param {module:api/CookingsApi~getCookingsCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link Array.<module:model/Cooking>}
     */
    this.getCookings = function(callback) {
      var postBody = null;


      var pathParams = {
      };
      var queryParams = {
      };
      var collectionQueryParams = {
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = [Cooking];

      return this.apiClient.callApi(
        '/cookings', 'GET',
        pathParams, queryParams, collectionQueryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
