/**
 * KilnRegulator
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Sample'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('./Sample'));
  } else {
    // Browser globals (root is window)
    if (!root.KilnRegulator) {
      root.KilnRegulator = {};
    }
    root.KilnRegulator.Cooking = factory(root.KilnRegulator.ApiClient, root.KilnRegulator.Sample);
  }
}(this, function(ApiClient, Sample) {
  'use strict';




  /**
   * The Cooking model module.
   * @module model/Cooking
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Cooking</code>.
   * @alias module:model/Cooking
   * @class
   */
  var exports = function() {
    var _this = this;






  };

  /**
   * Constructs a <code>Cooking</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Cooking} obj Optional instance to populate.
   * @return {module:model/Cooking} The populated <code>Cooking</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('uuid')) {
        obj['uuid'] = ApiClient.convertToType(data['uuid'], 'String');
      }
      if (data.hasOwnProperty('programId')) {
        obj['programId'] = ApiClient.convertToType(data['programId'], 'String');
      }
      if (data.hasOwnProperty('startDate')) {
        obj['startDate'] = ApiClient.convertToType(data['startDate'], 'Date');
      }
      if (data.hasOwnProperty('samples')) {
        obj['samples'] = ApiClient.convertToType(data['samples'], [Sample]);
      }
      if (data.hasOwnProperty('error')) {
        obj['error'] = ApiClient.convertToType(data['error'], 'String');
      }
    }
    return obj;
  }

  /**
   * UUID of this cooking
   * @member {String} uuid
   */
  exports.prototype['uuid'] = undefined;
  /**
   * Program UUID used for this cooking
   * @member {String} programId
   */
  exports.prototype['programId'] = undefined;
  /**
   * Date and time when this cooking started
   * @member {Date} startDate
   */
  exports.prototype['startDate'] = undefined;
  /**
   * @member {Array.<module:model/Sample>} samples
   */
  exports.prototype['samples'] = undefined;
  /**
   * If present something bad happened
   * @member {String} error
   */
  exports.prototype['error'] = undefined;



  return exports;
}));


