/**
 * KilnRegulator
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.1.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.3.1
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.KilnRegulator) {
      root.KilnRegulator = {};
    }
    root.KilnRegulator.Segment = factory(root.KilnRegulator.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The Segment model module.
   * @module model/Segment
   * @version 0.1.0
   */

  /**
   * Constructs a new <code>Segment</code>.
   * @alias module:model/Segment
   * @class
   */
  var exports = function() {
    var _this = this;




  };

  /**
   * Constructs a <code>Segment</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Segment} obj Optional instance to populate.
   * @return {module:model/Segment} The populated <code>Segment</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('targetTemperature')) {
        obj['targetTemperature'] = ApiClient.convertToType(data['targetTemperature'], 'Number');
      }
      if (data.hasOwnProperty('slope')) {
        obj['slope'] = ApiClient.convertToType(data['slope'], 'Number');
      }
      if (data.hasOwnProperty('duration')) {
        obj['duration'] = ApiClient.convertToType(data['duration'], 'Number');
      }
    }
    return obj;
  }

  /**
   * target temperature at the end of the segment
   * @member {Number} targetTemperature
   */
  exports.prototype['targetTemperature'] = undefined;
  /**
   * slope in °C/second
   * @member {Number} slope
   */
  exports.prototype['slope'] = undefined;
  /**
   * duration in seconds
   * @member {Number} duration
   */
  exports.prototype['duration'] = undefined;



  return exports;
}));


